### ISSUE TITLE
Not be able to set Vertical Orientation for this Flow Layout

### ISSUE THREAD

**Issue by Jay268** [nex3z/FlowLayout#11]
@nex3z 

I am using your flow layout to display content in my app. However it is working as intended but what i want is right now the flow is by default in Horizontal orientation displayed. 

What if i want it in Vertical Orientation i am not be able to identify how can i do it ?

Any help will be appreciated.

**Comment by nex3z** [comment]
Sorry to tell you that `FlowLayout` only support horizontal orientation. It's not possible to layout child views in vertical orientation.

I think it might be easier to modify the existing code to make it a vertical-orientation only one. Accumulate child view's height (instead of child view's width) and compare it against parent's height  (instead of parent's width)  to decide which column (instead of row) should it belong, compute child spacing if necessary, then layout child views vertically (instead of horizontally).

Feel free to fork the repo and modify the code :kissing_heart:.
