### ISSUE TITLE
Overflow items?

### ISSUE THREAD

**Issue by nabinadhikari** [nex3z/FlowLayout#23]
Hi, 
If there are more items after second row, is there a easy to indicate that there are more items to list (just like ellipsize)?

**Comment by nex3z** [comment]
I think this might need some extra calculation because adding the ellipsize token would change the size of the current row. 

For example, if there are more items after second row, and you want an ellipsize token to be shown at the end of the second row:
- If there is enough space for the ellipsize token in the second row, insert the ellipsize token to the right of the last item in the second row;
- If there is no enough space for the ellipsize token, insert the ellipsize token to the left of the last item in the second row, and the original last item in the second row will be flowed to the third row.
