### ISSUE TITLE
Showing JavaCompile Error while building app

### ISSUE THREAD

**Issue by Ganeshpokale1988** [nex3z/FlowLayout#32]
WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompile(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
Affected Modules: flowlayout

**Comment by nex3z** [comment]
I couldn't reproduce this warning with current code on master branch.
Have you modified build.gradle, or updated Gradle and/or Android Gradle plugin?

**Comment by Ganeshpokale1988** [comment]
Update Android studio and check

**Comment by nex3z** [comment]
Tried Android Studio 3.4.1 and no warning occurred.

![Screen Shot 2019-05-17 at 6 32 43 PM](https://user-images.githubusercontent.com/5645004/57922749-0b07bd80-78d3-11e9-98d6-4bd5ef251513.png)

After updating gradle from 4.6 to 5.1.1 and Android Gradle plugin from 3.2.1 to 3.4.1 as Android Studio 3.4.1 suggests, the warning occurred. This warning comes from bintray-release plugin by calling deprecated Gradle API. This issues should be fixed by future release of bintray-release plugin.
