### ISSUE TITLE
how could i know if i'd stop calling addView() when flMaxRows is set?

### ISSUE THREAD

**Issue by macarthor** [nex3z/FlowLayout#46]
hi,

we'd not know how many children could be displayed in the layout if flMaxRows is set.

so how could i know if i'd stop calling addView()?

many thanks.

**Comment by nex3z** [comment]
You don't need to stop calling addView() when using `flMaxRows`. Just set `flMaxRows` and add all the child views you have, all the calculation is done inside the FlowLayout.

For example, add `flMaxRows="2"` to the FlowLayout in  [sample](https://github.com/nex3z/FlowLayout/blob/master/sample/src/main/res/layout/activity_main.xml#L19):
```xml
<com.nex3z.flowlayout.FlowLayout
    android:id="@+id/flow"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:flChildSpacing="auto"
    app:flRowSpacing="8dp"
    app:flMaxRows="2"/>
```

Add all the 15 strings in [lorem_ipsum](https://github.com/nex3z/FlowLayout/blob/master/sample/src/main/res/values/arrays.xml#L3):
```java
final FlowLayout flowLayout = findViewById(R.id.flow);
String[] dummyTexts = getResources().getStringArray(R.array.lorem_ipsum);

for (String text : dummyTexts) {
    TextView textView = buildLabel(text);
    flowLayout.addView(textView);
}
```

Only 2 rows are shown:
![device-2021-01-29-221320](https://user-images.githubusercontent.com/5645004/106285312-4866d700-627f-11eb-9027-450e437a9855.png)

**Comment by macarthor** [comment]
@nex3z aye it works well. but after all we waste cycles and calculations.

**Comment by nex3z** [comment]
I think the calculation might not be alleviated much. After adding all the child views, FlowLayout's `onMeasure()` is triggered once. The calculation is done once and the complexity is linear. 

To achieve the goal of stop calling `addView()` manually when `flMaxRows` is met, FlowLayout needs to do the calculation every time a child view is added, in order to provide instant feedback whether the caller should stop adding more. The multiple cycle of calculation could introduce extra cost.

However, stop calling `addView()` manually when `flMaxRows` is met makes sense when it is very expensive to build each child view. In such scenario, if all child views have same width, then it is easy to pre-calculate the number of needed child views. Other solution would be to delay loading expensive resources on child views, until it is verified to be visible later.

**Comment by macarthor** [comment]
@nex3z aye you're right about calling addview() continuously in one message loop in a looper. the measure is done for all of them in the next message loop.

but i believe it's good to provide an API to tell if there's room for new views, considering horizontal spaces between views. suppose i have a paged network request or data fetching from persistent storage which should call addview in different message loops. i believe it's quite useful to know if i'd stop the expensive calls. by now i cannot know whether the FlowLayout can hold more views.

**Comment by nex3z** [comment]
Whether there is room for a new view depends on the size of it, which might not be determined until it is added to FlowLayout and then measured.

If all the views have same size and spacing, it's easy to precompute how many views are needed. 

With views with different sizes and `flRowSpacing=auto`, things are a bit tricky.

If the size of the new view is already determined, one solution is to query the remaining size for each row and then check whether there's enough room. By exposing [mWidthForRow](https://github.com/nex3z/FlowLayout/blob/master/flowlayout/src/main/java/com/nex3z/flowlayout/FlowLayout.java#L60) you can get the occupied size of each row, then it's easy to calculate the remaining size.

If the size of the new view is not determined, then it's trickier. I've made a quick and dirty solution in [Example.zip](https://github.com/nex3z/FlowLayout/files/5897559/Example.zip), making use of the current API.

The measuring can be quite complicated with different sized child views and auto spacing. FlowLayout is supposed to handle the complexity inside and I'll keep the API easy and simple for now.

**Comment by macarthor** [comment]
the point is, as a library, you don't know if the remaining horizontal space is enough for the new unknown view. it's up to the developer to decide if the remaining space is enough for his views.

but the library can provide an API `boolean hasHorizontalSpaceForLastRow(float expectedWidthPxExcludingPredefinedSpace)` which can be called by the developer. the library is cohesive for this API, instead of exposing the space outward. the predefined space between views is a fixed value at runtime. so i think such API is reasonable.

**Comment by nex3z** [comment]
I've added `int getRemainingSpaceForRow(int row)` to query remaining size of specific row in 1.3.4-beta, try

```
implementation 'com.nex3z:flow-layout:1.3.4-beta'
```

```java
val maxRows = 2
val dummyTexts = resources.getStringArray(R.array.lorem_ipsum)
var i = 0
btn_add.setOnClickListener {
    if (fl_container.getRemainingSpaceForRow(maxRows - 1) >= 200) {
        fl_container.addView(buildLabel(dummyTexts[i++ % dummyTexts.size]))
    } else {
        Log.v(TAG, "initView(): Not enough space")
    }
}
```
[Example.zip](https://github.com/nex3z/FlowLayout/files/5897942/Example.zip)

Note that all child views need to be measured before calling `getRemainingSpaceForRow()`, so that FlowLayout can compute all the sizes and spacings correctly.

**Comment by macarthor** [comment]
it's great to have a quick support. but i'll read carefully tomorrow...

btw, would you refactor with [Flow](https://developer.android.com/reference/androidx/constraintlayout/helper/widget/Flow)
